name: Build and Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Create build directory
      run: mkdir build
    - name: Installing meson and ninja
      run: python3 -m pip install meson ninja
    - name: Run meson configuration
      run: meson setup build
    - name: Building project
      run: ninja -C build
    - name: Running tests
      run: ninja test -C build