name: Build and Run Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Create build directory
      run: mkdir build
    - name: Installing meson and ninja
      run: python3 -m pip install meson ninja
    - name: Run meson configuration
      run: meson setup build
    - name: Building project
      run: ninja -C build
    - name: Copying roms
      run: cp ~/quickerNES/tests/roms/* tests/roms/
    - name: Running tests
      run: ninja test -C build
    - uses: actions/upload-artifact@v4
      with:
        name: meson-logs
        path: build/meson-logs/